#!/usr/bin/env python3
"""Build Aozix's self-contained, static GitHub organization profile assets.

Run from any directory with Python 3. No network, credentials, fonts, or
third-party dependencies are required. The generated SVGs contain no scripts.
"""
from __future__ import annotations

from html import escape
from math import cos, sin, pi
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / 'profile' / 'assets'
RAW = 'https://raw.githubusercontent.com/aozix-tech/.github/main/profile/assets'

PROFILE = f'''<!-- Generated by scripts/build-profile.py. Edit that file, then regenerate. -->
<p align="center">
  <a href="https://aozix.com/">
    <picture>
      <source media="(max-width: 600px)" srcset="{RAW}/hero-mobile.svg">
      <img src="{RAW}/hero.svg" width="1200" alt="Aozix Technology. Beyond ideas. Into reality. An independent technology studio building software, AI tools, and playful digital experiences.">
    </picture>
  </a>
</p>

<p align="center">
  <a href="https://aozix.com/"><strong>Visit our website ↗</strong></a>
  &nbsp; · &nbsp;
  <a href="https://x.com/aozixtech"><strong>Follow @aozixtech on X ↗</strong></a>
  &nbsp; · &nbsp;
  <a href="https://games.sshd.one/support/">Game support ↗</a>
</p>

## Independent thinking. Intentional building.

We're **Aozix**, an independent technology studio turning ideas into useful software and thoughtful digital experiences. We build for people, with a focus on clarity, craftsmanship, and the details that make a product feel right.

From web and mobile applications to practical AI tools and approachable games, we stay curious and keep making things better.

### Different possibilities. One maker mindset.

<picture>
  <source media="(max-width: 600px)" srcset="{RAW}/focus-mobile.svg">
  <img src="{RAW}/focus.svg" width="1200" alt="BUILD: Software with purpose — web platforms and mobile applications built around real needs. EXPLORE: Intelligence, applied — practical AI tools and automation for meaningful work. PLAY: A little more delight — approachable games and thoughtful interactive experiences.">
</picture>

## Built to be experienced.

### Screw Factory: Bolt Sort

A fresh twist on sorting. A small puzzle, a satisfying solution. Explore the game, discover its world, and find product-specific support.

**[Discover the game ↗](https://games.sshd.one/screw-factory/)** &nbsp; · &nbsp; [Get support](https://games.sshd.one/support/)

### The next idea is taking shape.

New tools. Unexpected connections. We're exploring what comes next at the intersection of **AI, software, and human curiosity**.

[Explore Aozix ↗](https://aozix.com/#work) &nbsp; · &nbsp; [Follow the journey on X ↗](https://x.com/aozixtech)

## The Aozix way

**Build something useful, not just something new.**  
Start with a real need. Keep technology in service of the experience.

**Care about the details people can feel.**  
Clarity, reliability, and thoughtful interactions are part of the product.

**Stay curious. Keep making things better.**  
Listen, learn, and improve one detail at a time.

---

<p align="center">
  <strong>Small studio. Open horizons.</strong><br>
  <sub>Thoughtfully built. Always evolving.</sub>
</p>

<p align="center">
  <a href="https://aozix.com/">aozix.com</a>
  &nbsp; / &nbsp;
  <a href="https://x.com/aozixtech">X · @aozixtech</a>
  &nbsp; / &nbsp;
  <a href="https://games.sshd.one/privacy/">Game privacy</a>
</p>
'''


def text(x: float, y: float, value: str, size: int = 20,
         fill: str = '#a9a3b8', weight: str = '400', extra: str = '') -> str:
    return (f'<text x="{x}" y="{y}" fill="{fill}" font-size="{size}" '
            f'font-weight="{weight}" {extra}>{escape(value)}</text>')


def defs() -> str:
    return '''<defs>
<linearGradient id="accent" x1="0" y1="0" x2="1" y2="0"><stop stop-color="#efe4ff"/><stop offset=".46" stop-color="#bea2ff"/><stop offset="1" stop-color="#88acff"/></linearGradient>
<linearGradient id="wire" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#bb99ff"/><stop offset=".55" stop-color="#bca4f2"/><stop offset="1" stop-color="#77a6ff"/></linearGradient>
<radialGradient id="glow"><stop stop-color="#5a3585" stop-opacity=".34"/><stop offset=".6" stop-color="#37224f" stop-opacity=".15"/><stop offset="1" stop-color="#07080c" stop-opacity="0"/></radialGradient>
<linearGradient id="panel" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#15121f"/><stop offset="1" stop-color="#0b0c12"/></linearGradient>
</defs>'''


def wrap(width: int, height: int, title: str, description: str, body: str) -> str:
    return (f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" '
            f'viewBox="0 0 {width} {height}" role="img" aria-labelledby="title desc">\n'
            f'<title id="title">{escape(title)}</title><desc id="desc">{escape(description)}</desc>\n'
            + defs() + '\n<g font-family="Helvetica Neue, Arial, sans-serif">\n'
            + body + '\n</g></svg>\n')


def orbit(cx: int, cy: int, scale: float) -> str:
    """Orthographic torus curves, matching the website's particle sculpture."""
    ellipses = []
    for i in range(26):
        v = 2 * pi * i / 26
        r = 159 + 53 * cos(v)
        y = -53 * sin(v) * .81
        ellipses.append(f'<ellipse cx="0" cy="{y:.2f}" rx="{r:.2f}" ry="{r*.59:.2f}"/>')
    geometry = ''.join(ellipses)
    meridians = []
    for i in range(20):
        u = 2 * pi * i / 20
        points = []
        for j in range(41):
            v = 2 * pi * j / 40
            r = 159 + 53 * cos(v)
            x, y = r*cos(u), r*sin(u)*.59 - 53*sin(v)*.81
            points.append(f'{x:.1f},{y:.1f}')
        meridians.append('<polyline points="' + ' '.join(points) + '"/>')
    return (f'<g transform="translate({cx} {cy}) rotate(-28) scale({scale})" fill="none">'
            '<g stroke="url(#wire)" stroke-width=".7" opacity=".38">' + geometry + '</g>'
            '<g stroke="#c8b6ff" stroke-width="2" stroke-linecap="round" stroke-dasharray=".01 13" opacity=".50">' + geometry + '</g>'
            '<g stroke="url(#wire)" stroke-width=".5" opacity=".17">' + ''.join(meridians) + '</g></g>')


def logo(x: int, y: int, size: int = 38) -> str:
    # Reuse the original A mark from the public Aozix website.
    return (f'<g transform="translate({x} {y}) scale({size/38})" fill="url(#accent)">'
            '<path d="M16 2h7L8 35H1L16 2Zm7 14 10 19h-8l-6-12 4-7ZM11 27h12l3 6H8l3-6Z"/></g>')


def hero(mobile: bool = False) -> str:
    width, height = (640, 710) if mobile else (1200, 440)
    x = 42 if mobile else 58
    body = f'<rect x=".5" y=".5" width="{width-1}" height="{height-1}" rx="24" fill="#07080c" stroke="#282133"/>\n'
    body += f'<ellipse cx="{330 if mobile else 909}" cy="{484 if mobile else 221}" rx="{330 if mobile else 345}" ry="270" fill="url(#glow)"/>'
    body += logo(x, 34)
    body += text(x+49, 63, 'aozix', 34, '#f0ecf6', '600', 'letter-spacing="-1.5"')
    body += text(x+151, 61, 'TECHNOLOGY', 11, '#a39bb5', extra='letter-spacing="2.2"')
    body += f'<circle cx="{x+3}" cy="{111 if mobile else 117}" r="3" fill="#bca4ff"/>'
    body += text(x+17, 115 if mobile else 121, 'INDEPENDENT TECHNOLOGY STUDIO', 12, '#bbb2ce', extra='letter-spacing="2.1"')
    body += text(x, 190 if mobile else 201, 'Beyond ideas.', 68 if mobile else 78, '#f1eff7', '500', 'letter-spacing="-3.2"')
    body += text(x, 265 if mobile else 281, 'Into reality.', 68 if mobile else 78, 'url(#accent)', '500', 'letter-spacing="-3.2"')
    if mobile:
        body += text(x, 311, 'Thoughtful software. Useful AI.', 23)
        body += text(x, 343, 'Playful digital experiences.', 23)
        body += orbit(335, 503, .81)
        body += '<path d="M42 650H598" stroke="#2a2237"/>'
        body += text(42, 681, 'SOFTWARE / AI / GAMES', 12, '#a29ab4', extra='letter-spacing="1.5"')
        body += text(598, 681, 'aozix.com', 15, '#ddd0f1', extra='text-anchor="end"')
    else:
        body += text(x, 326, 'Thoughtful software. Useful AI. Playful experiences.', 21)
        body += orbit(918, 228, .88)
        body += text(755, 65, 'FIG. A—01 / IDEAS IN MOTION', 10, '#a39ab6', extra='letter-spacing="1.7"')
        body += '<path d="M58 385H1142" stroke="#292232"/>'
        body += text(x, 414, 'SOFTWARE   /   APPLIED AI   /   DIGITAL EXPERIENCES', 11, '#a29ab4', extra='letter-spacing="1.7"')
        body += text(1142, 414, 'aozix.com', 15, '#ddd0f1', extra='text-anchor="end"')
    return wrap(width, height, 'Aozix — Beyond ideas. Into reality.',
                'Independent technology studio. Software, AI tools, and digital experiences. Lavender and ice-blue orbital artwork on an obsidian background.', body)


def icon(kind: int, x: int, y: int) -> str:
    start = f'<g transform="translate({x} {y})" fill="none" stroke="#baa5ec" stroke-width="1.6">'
    if kind == 0:
        content = '<path d="M0 20 24 7 48 20 24 34ZM0 30l24 14 24-14M0 40l24 14 24-14"/>'
    elif kind == 1:
        content = '<path d="M7 8 26 29 47 8M7 50l19-21 21 21"/><circle cx="26" cy="29" r="10" fill="#211831"/><circle cx="7" cy="8" r="4"/><circle cx="47" cy="8" r="4"/><circle cx="7" cy="50" r="4"/><circle cx="47" cy="50" r="4"/>'
    else:
        content = '<rect x="0" y="10" width="53" height="38" rx="11"/><path d="M9 29h16m-8-8v16"/><circle cx="37" cy="25" r="2" fill="#9dc7ef"/><circle cx="43" cy="34" r="2" fill="#9dc7ef"/>'
    return start + content + '</g>'


def focus(mobile: bool = False) -> str:
    width, height = (640, 652) if mobile else (1200, 244)
    cards = [
        ('01 / BUILD', 'Software with purpose.', 'Web platforms and mobile apps,', 'shaped around real needs.'),
        ('02 / EXPLORE', 'Intelligence, applied.', 'Practical AI tools and automation', 'for more meaningful work.'),
        ('03 / PLAY', 'A little more delight.', 'Approachable games and thoughtful', 'interactive experiences.'),
    ]
    body = ''
    for i, (label, title, line1, line2) in enumerate(cards):
        x, y, w, h = (0, i*224, 640, 204) if mobile else (i*408, 0, 384, 244)
        body += f'<g transform="translate({x} {y})"><rect x=".5" y=".5" width="{w-1}" height="{h-1}" rx="18" fill="url(#panel)" stroke="#302638"/>'
        body += f'<path d="M27 1H{w-27}" stroke="url(#accent)" opacity=".45"/>'
        body += text(29, 42, label, 12, '#b8a4d9', extra='letter-spacing="2"')
        body += icon(i, w-93, 17)
        body += text(29, 98 if mobile else 116, title, 30 if mobile else 27, '#ece6f5', '500', 'letter-spacing="-.7"')
        body += text(29, 140 if mobile else 161, line1, 23 if mobile else 19)
        body += text(29, 174 if mobile else 191, line2, 23 if mobile else 19)
        body += '</g>'
    return wrap(width, height, 'What we build', 'Software with purpose. Intelligence, applied. A little more delight.', body)


def main() -> None:
    ASSETS.mkdir(parents=True, exist_ok=True)
    (ROOT / 'profile' / 'README.md').write_text(PROFILE, encoding='utf-8')
    for name, svg in {'hero.svg': hero(), 'hero-mobile.svg': hero(True),
                      'focus.svg': focus(), 'focus-mobile.svg': focus(True)}.items():
        (ASSETS / name).write_text(svg, encoding='utf-8')
        print(f'Generated profile/assets/{name}')


if __name__ == '__main__':
    main()
